import { showModalMessage } from '../controller/global/modal';
import { showError, showSuccess } from '../controller/global/notification';
import {
  buildEntityActionURL,
  buildOverviewHighlightURL,
  navigateToURL,
} from '../controller/global/url';
import { isTriggable } from '../utils/actionUtils';
import { sendRequest } from '../utils/authRequest';
import { isNameGeneratedByYAC, isNameOptionalByYAC } from '../utils/nameUtils';
import { entityToastTitle, operationSuccessText } from '../utils/toastUtils';
import { ActionDecl } from '../utils/types/api';
import { OperationsMetaInfo } from '../utils/types/internal/actions';
import { RequestContext } from '../utils/types/internal/request';
import { Nullable } from '../utils/types/typeUtils';
import { joinUrl } from '../utils/urlUtils';
import { copyEntity } from './copy';
import { deleteEntity } from './delete';
import { invalidateEntityListCache } from './entityList';
import { linkEntity } from './link';
import { handleYacResponse } from './utils/handleYacResponse';

/**
 * After an action that creates/changes an entity from the overview, refresh the
 * table (invalidate its cache) and point the URL at the affected entity so the
 * table scrolls to and highlights it. If the name is unknown (e.g. generated),
 * just return to the plain overview (the cache invalidation still reloads it).
 */
function reloadOverviewAtEntity(requestContext: RequestContext, entityName?: Nullable<string>) {
  invalidateEntityListCache(requestContext.yacURL, requestContext.entityTypeName);
  navigateToURL(
    buildOverviewHighlightURL(
      requestContext.backendObject?.name,
      requestContext.entityTypeName,
      entityName,
    ),
  );
}

export function getActionCallback(
  requestContext: RequestContext,
  entityName: string,
  actionObj: ActionDecl,
): () => Promise<boolean> {
  return async () => {
    const doAction = async () => {
      const successfullySubmitted = await sendAction(requestContext, entityName, actionObj);
      if (successfullySubmitted) {
        showSuccess(
          entityToastTitle(requestContext, entityName),
          `${actionObj.title} was successful!`,
        );
      } else if (successfullySubmitted == null) {
        // Skip, the error was printed
      } else {
        showError(
          entityToastTitle(requestContext, entityName),
          `${actionObj.title} failed!`,
        );
      }
    };
    if (actionObj.dangerous) {
      showModalMessage(
        `${actionObj.title} on ${entityName}?`,
        actionObj.description,
        doAction,
        async () => {},
        actionObj.title,
        false,
      );
    } else {
      await doAction();
    }

    return true;
  };
}

/**
 * @param permsAvailable The available permissions for this corresponding host.
 * @param permsRequ The required permissions for the corresponding action.
 * @returns Boolean, whether this action can be executed.
 */
export function checkPermissions(permsAvailable: string[], permsRequ: string[]): boolean {
  const setB = new Set(permsAvailable);
  return [...new Set(permsRequ)].filter((x) => setB.has(x)).length > 0;
}

/**
 * The list of operations, represented as action objects.
 *
 * This allows uniform treatment at the view level.
 */
export const OPERATIONS_META: OperationsMetaInfo = {
  /**
   * Copy operation. This operation copies an entity.
   **/
  create_copy: {
    getOperationCallback: (entityName: string, requestContext: RequestContext) => {
      return async () => {
        // When the name is enforced (generated by YAC), the copy must not offer
        // a name field; otherwise the user may enter (or omit) a name.
        const showNameField = !isNameGeneratedByYAC(requestContext.accessedEntityType);
        // An optional name is generated by YAC if left empty: hint this in the
        // placeholder. A required name ('never') gets no placeholder.
        const namePlaceholder = isNameOptionalByYAC(requestContext.accessedEntityType)
          ? 'Generate Automatically'
          : '';
        showModalMessage(
          `Create copy of ${entityName}?`,
          showNameField
            ? 'Please enter a name for the new copy:'
            : 'The name is generated automatically.',
          async (newName?: string, actionsSelected?: ActionDecl[]) => {
            const res = await copyEntity(
              newName,
              entityName,
              actionsSelected ?? [],
              requestContext,
            );
            if (res.success) {
              showSuccess(
                entityToastTitle(requestContext, res.name ?? newName),
                operationSuccessText(`Create copy of ${entityName}`, actionsSelected),
              );
              reloadOverviewAtEntity(requestContext, res.name ?? newName);
            } else if (res.success !== null) {
              showError(
                entityToastTitle(requestContext, entityName),
                `Create copy of ${entityName} failed!`,
              );
            }
          },
          async () => {},
          'Create Copy',
          showNameField,
          requestContext.accessedEntityType?.actions.filter((v) => isTriggable('create', v)),
          namePlaceholder,
        );
        return true;
      };
    },
  },
  /**
   * Edit operation. This operation modifies an existing entity.
   *
   */
  edit: {
    getOperationURL: (entityName: string, requestContext: RequestContext) =>
      buildEntityActionURL(
        requestContext.backendObject?.name,
        requestContext.entityTypeName,
        'edit',
        entityName,
      ),
    getOperationCallback: (entityName: string, requestContext: RequestContext) => {
      return async () => {
        navigateToURL(
          buildEntityActionURL(
            requestContext.backendObject?.name,
            requestContext.entityTypeName,
            'edit',
            entityName,
          ),
        );
        return true;
      };
    },
  },
  /**
   * Read operation. The replacement of edit if the latter is not permitted to the user.
   *
   */
  read: {
    getOperationURL: (entityName: string, requestContext: RequestContext) =>
      buildEntityActionURL(
        requestContext.backendObject?.name,
        requestContext.entityTypeName,
        'read',
        entityName,
      ),
    getOperationCallback: (entityName: string, requestContext: RequestContext) => {
      return async () => {
        navigateToURL(
          buildEntityActionURL(
            requestContext.backendObject?.name,
            requestContext.entityTypeName,
            'read',
            entityName,
          ),
        );
        return true;
      };
    },
  },
  /**
   * Delete operation. This operation deletes an entity.
   */
  delete: {
    getOperationCallback: (entityName: string, requestContext: RequestContext) => {
      return async () => {
        const del = async (_enteredName?: string, actionsSelected?: ActionDecl[]) => {
          const success = await deleteEntity(entityName, requestContext, actionsSelected);
          if (success) {
            // TODO: Need to change the cachin structure...
            invalidateEntityListCache(requestContext.yacURL, requestContext.entityTypeName);
            showSuccess(
              entityToastTitle(requestContext, entityName),
              operationSuccessText(`Delete of ${entityName}`, actionsSelected),
            );
            // If the deleted entity is the one pinned in the URL (?name=...),
            // drop the pin: the list reload would otherwise treat it as
            // "doesn't exist yet" and forward to the create form.
            if (new URLSearchParams(window.location.search).get('name') === entityName) {
              navigateToURL(
                buildOverviewHighlightURL(
                  requestContext.backendObject?.name,
                  requestContext.entityTypeName,
                ),
              );
            }
            return;
          }
          if (success == null) return;
          showError(
            entityToastTitle(requestContext, entityName),
            `Delete of ${entityName} failed!`,
          );
        };
        showModalMessage(
          `Delete ${entityName}?`,
          OPERATIONS['delete'].description,
          del,
          async () => {},
          'Delete',
          false,
          requestContext.accessedEntityType?.actions.filter((v) => isTriggable('delete', v)),
        );

        return true;
      };
    },
  },
  /**
   * Linking operation. Creates a link to an existing entity.
   **/
  create_link: {
    getOperationCallback: (entityName: string, requestContext: RequestContext) => {
      return async () => {
        // When the name is enforced (generated by YAC), the link must not offer
        // a name field; otherwise the user may enter (or omit) a name.
        const showNameField = !isNameGeneratedByYAC(requestContext.accessedEntityType);
        // An optional name is generated by YAC if left empty: hint this in the
        // placeholder. A required name ('never') gets no placeholder.
        const namePlaceholder = isNameOptionalByYAC(requestContext.accessedEntityType)
          ? 'Generate Automatically'
          : '';
        showModalMessage(
          `Create link to ${entityName}?`,
          showNameField
            ? 'Please enter a name for the new link:'
            : 'The name is generated automatically.',
          async (newName?: string, actionsSelected?: ActionDecl[]) => {
            const res = await linkEntity(
              newName,
              entityName,
              actionsSelected ?? [],
              requestContext,
            );
            if (res.success) {
              showSuccess(
                entityToastTitle(requestContext, res.name ?? newName),
                operationSuccessText(`Create link to ${entityName}`, actionsSelected),
              );
              reloadOverviewAtEntity(requestContext, res.name ?? newName);
            } else if (res.success !== null) {
              showError(
                entityToastTitle(requestContext, entityName),
                `Create link to ${entityName} failed!`,
              );
            }
          },
          async () => {},
          'Create Link',
          showNameField,
          requestContext.accessedEntityType?.actions.filter((v) => isTriggable('create', v)),
          namePlaceholder,
        );

        return true;
      };
    },
  },
};

/**
 * View is a special operation which is not explicitly configured from the YAC side.
 * It is the replacement of the edit Operation if the user does not have
 * write permission.
 *
 * This behavior is different from the other actions/operations: They are typically greyed
 * out when not available.
 */
export const OPERATION_VIEW: ActionDecl = {
  name: 'read',
  title: 'Read',
  perms: ['see'], // && !edt
  icon: '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="grey"><path d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z"/></svg>',
  dangerous: false,
  force: true,
  hooks: [],
  description: '',
};

export const OPERATIONS: { [key: string]: ActionDecl } = {
  create_copy: {
    name: 'create_copy',
    title: 'Create Copy',
    perms: ['cpy'],
    icon: '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="grey"><path d="M120-220v-80h80v80h-80Zm0-140v-80h80v80h-80Zm0-140v-80h80v80h-80ZM260-80v-80h80v80h-80Zm100-160q-33 0-56.5-23.5T280-320v-480q0-33 23.5-56.5T360-880h360q33 0 56.5 23.5T800-800v480q0 33-23.5 56.5T720-240H360Zm0-80h360v-480H360v480Zm40 240v-80h80v80h-80Zm-200 0q-33 0-56.5-23.5T120-160h80v80Zm340 0v-80h80q0 33-23.5 56.5T540-80ZM120-640q0-33 23.5-56.5T200-720v80h-80Zm420 80Z"/></svg>',
    dangerous: false,
    force: true,
    hooks: [],
    description: '',
  },
  edit: {
    name: 'edit',
    title: 'Edit',
    perms: ['edt'],
    icon: '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="grey"><path d="M200-200h57l391-391-57-57-391 391v57Zm-80 80v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm640-584-56-56 56 56Zm-141 85-28-29 57 57-29-28Z"/></svg>',
    dangerous: false,
    force: true,
    hooks: [],
    description: '',
  },
  delete: {
    name: 'delete',
    title: 'Delete',
    perms: ['del'],
    icon: '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="grey"><path d="M280-120q-33 0-56.5-23.5T200-200v-520h-40v-80h200v-40h240v40h200v80h-40v520q0 33-23.5 56.5T680-120H280Zm400-600H280v520h400v-520ZM360-280h80v-360h-80v360Zm160 0h80v-360h-80v360ZM280-720v520-520Z"/></svg>',
    dangerous: true,
    force: true,
    hooks: [],
    description: `This action cannot be undone without admin support.`,
  },
  create_link: {
    name: 'create_link',
    title: 'Create Link',
    perms: ['lnk'],
    icon: '<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="grey"><path d="M680-160v-120H560v-80h120v-120h80v120h120v80H760v120h-80ZM440-280H280q-83 0-141.5-58.5T80-480q0-83 58.5-141.5T280-680h160v80H280q-50 0-85 35t-35 85q0 50 35 85t85 35h160v80ZM320-440v-80h320v80H320Zm560-40h-80q0-50-35-85t-85-35H520v-80h160q83 0 141.5 58.5T880-480Z"/></svg>',
    dangerous: false,
    force: true,
    hooks: [],
    description: `A link is a new 'shallow' copy which takes all values from its source (also when they change later on).`,
  },
};

/**
 * @param requestContext
 * @param entityName
 * @param actionObj
 * @returns
 */
export async function sendAction(
  requestContext: RequestContext,
  entityName: string,
  actionObj: ActionDecl,
): Promise<Nullable<boolean>> {
  const url: string | null | undefined = requestContext.yacURL;

  if (url == undefined || url == null) return false;

  const resp: Nullable<Response> = await sendRequest(
    joinUrl(url, `/entity/${requestContext.entityTypeName}/${entityName}/run/${actionObj.name}`),
    'POST',
  );

  const result = await handleYacResponse(resp, {
    title: entityToastTitle(requestContext, entityName),
    errorText: `${actionObj.title} failed`,
    successStatus: 204,
    genericClientErrors: true,
    // YAC sends a user-facing message for every status except 401/500 (see
    // YAC's error handler); a 5xx only carries a generic apology, so it gets
    // the plain "failed!".
    errorDetail: (status, body) =>
      status < 500 && body.message
        ? `${actionObj.title} failed:\n${body.message}`
        : `${actionObj.title} failed!`,
  });

  if (result.kind === 'success') return true;
  if (result.kind === 'network-error') return false;
  // The error was already reported (toast or re-login flow).
  return null;
}
