import { actions2URLQuery } from '../utils/actionUtils';
import { sendRequest } from '../utils/authRequest';
import { ActionDecl, NameGeneratedCond } from '../utils/types/api';
import { RequestContext } from '../utils/types/internal/request';
import { Nullable } from '../utils/types/typeUtils';
import { joinUrl } from '../utils/urlUtils';
import { handleYacResponse } from './utils/handleYacResponse';

/**
 * Create a new entity derived from an existing one. A *copy* duplicates the
 * source's values; a *link* is a shallow copy that keeps following the source.
 * The two YAC requests only differ in the key carrying the source entity name.
 *
 * @param kind Whether to copy or link the source entity.
 * @param entityName The name for the new entity (may be undefined when YAC generates it).
 * @param sourceEntityName The entity to copy/link from.
 * @param actions The create-actions to trigger alongside.
 * @param requestContext The request context.
 * @returns `success: true` with the (possibly generated) name, `success: null`
 * when an error toast was already shown, `success: false` otherwise.
 */
export async function createDerivedEntity(
  kind: 'copy' | 'link',
  entityName: string | undefined,
  sourceEntityName: string,
  actions: ActionDecl[],
  requestContext: RequestContext,
): Promise<{ success: Nullable<boolean>; name: Nullable<string> }> {
  const url: string | null | undefined = requestContext.yacURL;

  if (url == undefined || url == null) return { success: false, name: null };

  // Decide what to send as the "name" depending on how YAC generates names.
  // In all cases the key must be present (sending null instead of omitting it),
  // otherwise YAC rejects the request with HTTP 422.
  const nameGenerated = requestContext.accessedEntityType?.name_generated;
  let name: string | null;
  if (nameGenerated === NameGeneratedCond.enforced) {
    // The name is always generated by YAC; the input field is hidden.
    name = null;
  } else if (nameGenerated === NameGeneratedCond.optional) {
    // The name may be generated by YAC: an empty input means "generate it".
    name = entityName ? entityName : null;
  } else {
    // name_generated === 'never': a name is mandatory.
    name = entityName ?? '';
  }

  const resp: Nullable<Response> = await sendRequest(
    joinUrl(url, `/entity/${requestContext.entityTypeName}${actions2URLQuery(actions)}`),
    'POST',
    JSON.stringify({ name, [kind]: sourceEntityName }),
  );

  const result = await handleYacResponse(resp, {
    backendTitle: requestContext.backendObject?.title,
    errorTitle: `Cannot ${kind === 'copy' ? 'Copy' : 'Link'} ${sourceEntityName}`,
    errorMessage: 'Waking up the admin, please stand by...',
    successStatus: 201,
    genericClientErrors: true,
  });

  if (result.kind === 'success') {
    // YAC returns the (possibly generated) name of the new entity.
    const ans = await result.resp.json();
    return { success: true, name: ans?.name ?? null };
  }
  if (result.kind === 'network-error') return { success: false, name: null };
  // The error was already reported (toast or re-login flow).
  return { success: null, name: null };
}

export async function copyEntity(
  entityName: string | undefined,
  copyEntityName: string,
  actions: ActionDecl[],
  requestContext: RequestContext,
): Promise<{ success: Nullable<boolean>; name: Nullable<string> }> {
  return createDerivedEntity('copy', entityName, copyEntityName, actions, requestContext);
}
