import { stringify } from 'yaml';
import { diffToastLink } from '../controller/global/diffViewer';
import { showError, showSuccess } from '../controller/global/notification';
import { actions2URLQuery } from '../utils/actionUtils';
import { sendRequest } from '../utils/authRequest';
import { entityToastTitle, operationSuccessText } from '../utils/toastUtils';
import { ActionDecl } from '../utils/types/api';
import { RequestContext } from '../utils/types/internal/request';
import { Nullable } from '../utils/types/typeUtils';
import { joinUrl } from '../utils/urlUtils';
import { handleYacResponse, yacErrorDetail } from './utils/handleYacResponse';

export async function createNewEntity(
  name: Nullable<string>,
  data: { [key: string]: unknown },
  requestContext: RequestContext,
  yaml?: string,
  acts: ActionDecl[] = [],
): Promise<{ success: boolean; name: Nullable<string> }> {
  const url = requestContext.yacURL;
  if (url == null || url == undefined) return { success: false, name: null };

  const resp = await sendRequest(
    joinUrl(url, `/entity/${requestContext.entityTypeName}${actions2URLQuery(acts)}`),
    'POST',
    JSON.stringify({
      // The key must be present (null instead of omitted), otherwise YAC
      // rejects the request with HTTP 422.
      name: name ?? null,
      yaml: yaml ?? `---\n# Automatically generated by VAYS\n\n${stringify(data)}`,
    }),
  );

  const errorText = name ? `Create of ${name} failed` : 'Create failed';
  const result = await handleYacResponse(resp, {
    title: entityToastTitle(requestContext, name),
    errorText,
    errorMessage: 'Please contact your admin on this issue.',
    serverErrorSuffix: 'The data you entered is cached for now.',
    successStatus: 201,
  });

  if (result.kind === 'success') {
    // YAC answers with a `Diff` object: the (possibly generated) name of the
    // new entity plus `patch`, the unified diff of the commit.
    const ans: { name?: string; patch?: string } = await result.resp.json();
    const createdName: Nullable<string> = ans?.name ?? name;
    showSuccess(
      entityToastTitle(requestContext, createdName),
      operationSuccessText(createdName ? `Create of ${createdName}` : 'Create', acts),
      diffToastLink(`Changes for ${createdName}`, ans?.patch),
    );
    return { success: true, name: createdName };
  } else if (result.kind === 'invalid-request') {
    showError(
      'Frontend Error',
      'Invalid specification used, cannot talk to YAC servers. Please report ID-NEW-SD-01.',
    );
  } else if (result.kind === 'client-error') {
    showError(
      entityToastTitle(requestContext, name),
      yacErrorDetail(errorText, result.status, result.body, 'Please try again.'),
    );
  }

  return { success: false, name: null };
}
