import { showError } from '../controller/global/notification';
import { actions2URLQuery } from '../utils/actionUtils';
import { sendRequest } from '../utils/authRequest';
import { ActionDecl, NameGeneratedCond } from '../utils/types/api';
import { RequestContext } from '../utils/types/internal/request';
import { Nullable } from '../utils/types/typeUtils';
import { joinUrl } from '../utils/urlUtils';

export async function linkEntity(
  entityName: string | undefined,
  copyEntityName: string,
  actions: ActionDecl[],
  requestContext: RequestContext,
) {
  const url: string | null | undefined = requestContext.yacURL;

  if (url == undefined || url == null) return false;

  // Decide what to send as the "name" depending on how YAC generates names.
  // In all cases the key must be present (sending null instead of omitting it),
  // otherwise YAC rejects the request with HTTP 422.
  const nameGenerated = requestContext.accessedEntityType?.name_generated;
  let name: string | null;
  if (nameGenerated === NameGeneratedCond.enforced) {
    // The name is always generated by YAC; the input field is hidden.
    name = null;
  } else if (nameGenerated === NameGeneratedCond.optional) {
    // The name may be generated by YAC: an empty input means "generate it".
    name = entityName ? entityName : null;
  } else {
    // name_generated === 'never': a name is mandatory.
    name = entityName ?? '';
  }

  const resp: Nullable<Response> = await sendRequest(
    joinUrl(url, `/entity/${requestContext.entityTypeName}${actions2URLQuery(actions)}`),
    'POST',
    JSON.stringify({ name, link: copyEntityName }),
  );
  if (resp == null) return false;

  if (resp?.status == 201) return true;
  if (resp?.status >= 400) {
    const ans = await resp.json();
    showError(
      `${requestContext.backendObject?.title}: ` +
        (ans.title ?? `Cannot Link ${copyEntityName} (Status ${resp.status})`),
      ans.message ?? 'Waking up the admin, please stand by...',
    );
    return null;
  }

  return false;
}
