/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Load-time ("eager") value generation for `random_string` controls.
 *
 * The renderer generates its initial value from a mount effect, but the
 * categorization layout only mounts the active tab's controls — a field on
 * another tab would get its value only when that tab is first opened, so the
 * YAML/save payload would silently miss it. This pass runs where schema
 * defaults are materialized (create-mode load, see `insertDefaults`): it walks
 * the ui_schema for `random_string` Controls and generates their values into
 * the data before the first validation, independent of what is mounted.
 *
 * The renderer stays responsible for everything after load (Regenerate,
 * manual edits, fields appearing later through schema changes): it skips its
 * own auto-generation when data is already present. Generated paths are
 * recorded so the renderer can tell a load-time generated value from one
 * stored in YAC (only the latter gets a confirmation dialog on Regenerate).
 */

import _ from 'lodash';
import {
  DEFAULT_RANDOM_STRING_FORMAT,
  DEFAULT_RANDOM_STRING_LENGTH,
  generateRandomString,
  RANDOM_STRING_FORMATS,
} from '../randomString';
import { ValidateResponse } from '../types/internal/validation';

// Dot-joined data paths generated by the last `injectEagerRandomStrings` run
// (matching JSON Forms' composed control paths). Session-scoped: reset by
// `beginPaneSession` on a new editing session.
const eagerGeneratedPaths = new Set<string>();

export function resetEagerGenerated(): void {
  eagerGeneratedPaths.clear();
}

/**
 * Whether the value at `path` came from the eager pass (one-shot: consuming
 * clears the mark; the caller latches the answer for its lifetime).
 */
export function consumeEagerGenerated(path: string): boolean {
  return eagerGeneratedPaths.delete(path);
}

/** '#/properties/a/properties/b' -> ['a', 'b'] (null for any other shape). */
function scopeToPath(scope: unknown): string[] | null {
  if (typeof scope !== 'string') return null;
  const parts = scope.split('/');
  if (parts[0] !== '#') return null;
  const path: string[] = [];
  for (let i = 1; i < parts.length; i += 2) {
    if (parts[i] !== 'properties' || parts[i + 1] === undefined) return null;
    path.push(parts[i + 1]);
  }
  return path;
}

function subschemaAt(schema: any, path: string[]): any {
  let node = schema;
  for (const key of path) {
    node = node?.properties?.[key];
  }
  return node;
}

/** Mirrors the renderer's option handling; null on a spec error (the renderer
 *  surfaces those when it mounts — nothing is generated here). */
function generateFromOptions(ropts: any): string | null {
  const format = ropts?.format ?? DEFAULT_RANDOM_STRING_FORMAT;
  if (!RANDOM_STRING_FORMATS.includes(format)) return null;
  if (format === 'custom' && typeof ropts?.charset !== 'string') return null;
  const length =
    typeof ropts?.length === 'number' && ropts.length > 0
      ? Math.floor(ropts.length)
      : DEFAULT_RANDOM_STRING_LENGTH;
  try {
    return generateRandomString(format, length, ropts?.charset);
  } catch {
    return null;
  }
}

function visit(element: any, basePath: string[], valResp: ValidateResponse): void {
  if (!element || typeof element !== 'object') return;

  if (element.type === 'Control') {
    const relPath = scopeToPath(element.scope);
    if (relPath === null) return;
    const path = [...basePath, ...relPath];

    if (element.options?.renderer === 'random_string') {
      const existing = _.get(valResp.data, path);
      const subschema = subschemaAt(valResp.json_schema, path);
      // Same guards as the renderer's auto-generation: an existing value or a
      // spec default wins over generation.
      if ((existing === undefined || existing === '') && subschema?.default === undefined) {
        const value = generateFromOptions(element.options?.renderer_options);
        if (value !== null) {
          _.set(valResp.data, path, value);
          eagerGeneratedPaths.add(path.join('.'));
        }
      }
    }

    // A nested object's sub-ui-schema (scopes relative to the object).
    // `options.details` (array rows) is intentionally skipped: rows only
    // exist once the user adds them, and their controls mount right away.
    if (element.options?.detail) {
      visit(element.options.detail, path, valResp);
    }
    return;
  }

  if (Array.isArray(element.elements)) {
    for (const child of element.elements) {
      visit(child, basePath, valResp);
    }
  }
}

/**
 * Generate values for all `random_string` controls into `valResp.data`
 * (mutated in place, like `insertDefaults`). Call before the first
 * validation round-trip so the values reach the canonical data/YAML.
 */
export function injectEagerRandomStrings(valResp: ValidateResponse): void {
  visit(valResp.ui_schema, [], valResp);
}
